name: onpush
on: [push]
jobs:
  pre-build:
    name: pre-build validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: run php-cs-fixer
        run: make lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Test
        run: make test
