name: onpush
on: [push]
jobs:
  integration-pipeline:
    name: Integration pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15.0
      - name: Pre-build validations
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
